config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'casas/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "casas#index"

  resources :casas

  resources :users, only: [:show]
end

app/models/casa.rb
class Casa < ApplicationRecord
  belongs_to :user
  has_many :casa_facilities
  has_many :facilities, through: :casa_facilities
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  has_many :shared_rooms
  has_many :private_rooms

end

app/controllers/casas_controller.rb
class CasasController < ApplicationController
before_action :set_casa, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @casa = Casa.new
    @casa.images.new
  end

  def create
    @casa = Casa.new(casa_params)
    if @casa.save

    else
      render :new
    end
  end

  def edit
    @casa.images.new
  end

  def update
    if @casa.update(casa_params)
      redirect_to casa_path(params[:id])
    else
      render :edit
    end
  end

  def show
  end

  private

  def casa_params
    params.require(:casa).permit(:name, :information, :important_information, :detail, :location, :cancel, :policy, :check_in, :check_out, :description, :latitude, :longitude, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_casa
    @casa = Casa.find(params[:id])
  end

end

app/views/casas/_footer.html.haml
.footer__content
  .footer__content-upper
    %ul.footer__content-upper-lists
      %li.footer__list
        %span About Us
      %li.footer__list
        %span Work With Us
      %li.footer__list
        %span Customer Service
      %li.footer__list
        %span Website Feedback
  .footer__content-middle
    = image_tag "google-play-badge.png", class: "footer_icon-google", alt: "gooogle play"
    = image_tag "Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg", class: "footer_icon-apple", alt: "apple store"
  .footer__content-rower
    %span ©casa blanca
.footer__mobile
  .footer__mobile-upper
    %span casa blanca
  .footer__mobile-middle
    = image_tag "google-play-badge.png", class: "footer_icon-google", alt: "gooogle play"
    = image_tag "Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg", class: "footer_icon-apple", alt: "apple store"
  .footer__mobile-rower
    %span ©casa blanca

app/views/casas/_form.html.haml
.main-form__field
  =form_with model: @casa, local: true do |f|
    %h2.main-form__field__title
      Edit Your Information
    .main-form__field__text
      = f.label :name, class: "main-form__field__text-label"
      = f.text_field :name, placeholder: 'casa name', class: "main-form__field__text-form"
    .main-form__field__text
      = f.label :description, class: "main-form__field__text-label"
      = f.text_field :description, class: 'input-box__description', placeholder: "put address and click search button"
      = icon("fas","search-location", id: "searchAddressBtn")
    .map-area
      #map{:style => "width: 400px; height: 300px;"}
    .description-box
      = f.text_field :latitude, id: "post_latitude", readonly: "readonly"
      =f.text_field :longitude, id: "post_longitude", readonly: "readonly"
    .main-form__field__text
      =f.label :information, class: "main-form__field__text-label"
      =f.text_area :information, placeholder: "main information", class: "main-form__field__text-form"
    .main-form__field__images
      %p.main-form__field__images-title
        Upload your images
        - if @casa.persisted?
          #image-box
            #previews
              - @casa.images.each_with_index do |image, i|
                - if image.persisted?
                  .preview-box{id: "preview-box__#{i}"}
                    .upper-box
                      =image_tag image.src.url, data: { index: i}, class: "preview-image", alt: "preview"
                    .lower-box
                      .delete-box-edit{id: "delete_btn_#{i}"}
                        %span delete
            #labels
              = f.fields_for :images do |image|
                #label_edit{class: "label-content^#{image.index}"}
                  = image.label :src ,{id: "label-box--#{image.index}", class: "js-file_group", "data-index" => "#{image.index}"} do
                    =icon("fas", "camera", class: "label-box-icon")
                    %pre.label-box__text-visible
                    upload %image
                    =image.file_field :src, class: 'js-file', name: "casa[images_attributes][#{image.index}][src]"
                    = image.check_box :_destroy, data:{ index: image.index}, class: 'hidden-destroy'
            #deleted
        - else
          #image-box
            #previews
            #labels
              #label.label-content-0
                = f.fields_for :images do |image|
                  = image.label :src ,{id:"label-box--#{image.index}", class:"js-file_group", "data-index" => "#{image.index}"} do
                    =icon("fas","camera",class: "label-box-icon")
                    %pre.label-box__text-visible upload image
                    = image.file_field :src, class: 'js-file'
    -# .main-form__field__facilities
    -#   = f.label :facilities, class: "main-form__field__facilities-label"
    -#   = collection_check_boxes(:casa, :casa_facilities, Facility.all, :id, :facilityname) do |b|
    -#     = b.label { b.check_box + b.text }
    .main-form__field__important-information
      =f.label :important_information, class: "main-form__field__text-label"
      =f.text_area :important_information, placeholder: "important imformation", class: "main-form__field__text-form"
    .main-form__field__time
      = f.label :check_in
      = f.time_select :check_in, prompt:true, class: "main-form__field__time-select"
    .main-form__field__time
      = f.label :check_out
      = f.time_select :check_out, prompt:true, class: "main-form__field__time-select"
    .main-form__field__important-information
      =f.label :policy, class: "main-form__field__text-label"
      =f.text_area :policy, placeholder: "Policy", class: "main-form__field__text-form"
    .main-form__field__important-information
      =f.label :detail, class: "main-form__field__text-label"
      =f.text_area :detail, placeholder: "detail for your hostel", class: "main-form__field__text-form"
    .main-form__field__important-information
      =f.label :location, class: "main-form__field__text-label"
      =f.text_area :location, placeholder: "location imformation", class: "main-form__field__text-form"
    .main-form__field__important-information
      =f.label :cancel, class: "main-form__field__text-label"
      =f.text_area :cancel, placeholder: "cancel policy", class: "main-form__field__text-form"
    .main-form__field__submit
      = f.submit 'Next', class: "main-form__field__submit-btn"

app/views/casas/_header.html.haml
.header__nav
  = icon("fas","bars", class: "header__nav-icon")
.header__logo
  %h1 casa blanca
.header__menu
  %ul.header__menu__lists
    %li.menu__list
      Home
      %span /
    %li.menu__list
      Hostels
      %span /
    %li.menu__list
      Hotels
      %span /
    %li.menu__list
      Groups
      %span /
    %li.menu__list
      Blogs
.header__user
  -if user_signed_in?
    = link_to user_path(current_user) do
      = current_user.nickname
  -else
    = link_to new_user_session_path do
      Log in
.header__drop-menu.not-show
  .drop-menu
    %ul.drop-menu__lists
      %li.user-menu
        = icon("fas","laugh-wink", class: "user-menu__icon")
        .user-menu__text
          -if user_signed_in?
            = link_to user_path(current_user) do
              = current_user.nickname
          -else
            = link_to new_user_session_path do
              %span Log in
      %li.casa-menu
        casa
        %ul.casa-menu__lists
          %li.casa-menu__list
            Hostels
          %li.casa-menu__list
            Hotels
          %li.casa-menu__list
            Groups
          %li.casa-menu__list
            Blogs
      %li.help-menu
        help
        %ul.help-menu__lists
          %li.help-menu__list
            About Us
          %li.help-menu__list
            Work With Us
          %li.help-menu__list
            Customer Service
          %li.help-menu__list
            Website Feedback
    .drop-menu__btn
      = icon("fas","times", class: "drop-menu__btn-icon")

app/views/casas/create.html.haml
.header-form
  %h1.header-form__title
    =link_to root_path do
      %span casa blanca
.main-update
  .main-update__text
    completed
  .main-update__btn
    casa page

app/views/casas/edit.html.haml
.header-form
  %h1.header-form__title
    =link_to root_path do
      %span casa blanca
.main-form
  = render "form"

app/views/casas/index.html.haml
.header
  = render "header"
.main
  .main__upper
    .main__upper-slick
      .slick-list
        = image_tag "oia-416136_1920.jpg", class: "slick-list__image"
      .slick-list
        = image_tag "white-village-5361750_1920.jpg", class: "slick-list__image"
      .slick-list
        = image_tag "city-4820579_1920.jpg", class: "slick-list__image"
  .main__search-form
    %input.main__search-form__text{type: "text", placeholder: "Search by city or hostel name..."}
    %input.main__search-form__date-start{type: "date", value: "2020-01-01"}
    %input.main__search-form__date-end{type: "date", value: "2020-01-01"}
    %input.main__search-form__guest{type: "select", prompt: "Guest"}
    %input.main__search-form__btn{type: "submit", value: "Search"}
  .main__search-form-js
    %input.main__search-form-js{tyoe: "text", placeholder: "Search by city or hostel name..."}
  .main__search-form-mobile.not-show
    .search-mobile
      .search-mobile__title
        %span Search
      .search-mobile__input
        %input{type: "text", placeholder: "Search by city or hostel name..."}
      .search-mobile__close
        = icon("fas","times", class: "search-mobile__close-icon")
  .main__list
    .main__list__related-casa
      .main__list__related-casa-title
        %h2.main__list__related-casa-title-text
          %span Hostels you might like
        %p.main__list__related-casa-title-icon
          g
      %ul.main__list__related-casa-lists
        %li.main__list__related-casa-list-first
          = image_tag "japan-1366872_1920.jpg", class: "main__list__related-casa-list-first-image", alt: "casa-image"
          %h3.related-casa__place
            %span Japan
          .related-casa__info
            .related-casa__info-left
              %p.related-casa__info-left-name
                %span Hostel sample
              %p.related-casa__info-left-type
                %span Hostel
            .related-casa__info-right
              %p.related-casa__info-right-upper
                %span from
              %p.related-casa__info-right-middle
                %span 10.00
              %p.related-casa__info-right-rower
                %span USD
        %li.main__list__related-casa-list
          = image_tag "pool-720697_1280.jpg", class: "main__list__related-casa-list-image", alt: "casa-image"
          %h3.related-casa__place
            %span United States
          .related-casa__info
            .related-casa__info-left
              %p.related-casa__info-left-name
                %span Hostel sample
              %p.related-casa__info-left-type
                %span Hostel
            .related-casa__info-right
              %p.related-casa__info-right-upper
                %span from
              %p.related-casa__info-right-middle
                %span 10.00
              %p.related-casa__info-right-rower
                %span USD
        %li.main__list__related-casa-list
          = image_tag "window-3178666_1920.jpg", class: "main__list__related-casa-list-image", alt: "casa-image"
          %h3.related-casa__place
            %span Georgia
          .related-casa__info
            .related-casa__info-left
              %p.related-casa__info-left-name
                %span Hostel sample
              %p.related-casa__info-left-type
                %span Hostel
            .related-casa__info-right
              %p.related-casa__info-right-upper
                %span from
              %p.related-casa__info-right-middle
                %span 10.00
              %p.related-casa__info-right-rower
                %span USD
        %li.main__list__related-casa-list
          = image_tag "castle-park-806854_1920.jpg", class: "main__list__related-casa-list-image", alt: "casa-image"
          %h3.related-casa__place
            %span UK
          .related-casa__info
            .related-casa__info-left
              %p.related-casa__info-left-name
                %span Hostel sample
              %p.related-casa__info-left-type
                %span Hostel
            .related-casa__info-right
              %p.related-casa__info-right-upper
                %span from
              %p.related-casa__info-right-middle
                %span 10.00
              %p.related-casa__info-right-rower
                %span USD
        %li.main__list__related-casa-list
          = image_tag "beach-house-1505461_1920.jpg", class: "main__list__related-casa-list-image", alt: "casa-image"
          %h3.related-casa__place
            %span Cambosia
          .related-casa__info
            .related-casa__info-left
              %p.related-casa__info-left-name
                %span Hostel sample
              %p.related-casa__info-left-type
                %span Hostel
            .related-casa__info-right
              %p.related-casa__info-right-upper
                %span from
              %p.related-casa__info-right-middle
                %span 10.00
              %p.related-casa__info-right-rower
                %span USD
    .main__list__recommend
      .main__list__recommend-title
        %h2.main__list__recommend-title-text
          %span Top Destinations
      %ul.main__list__recommend-lists
        %li.main__list__recommend-list
          = image_tag "canal-1209808_1920.jpg", class: "main__list__recommend-list-image", alt: "place-image"
          %p.recommend-place-name
            %span Italy
        %li.main__list__recommend-list
          = image_tag "water-4848741_1920.jpg", class: "main__list__recommend-list-image", alt: "place-image"
          %p.recommend-place-name
            %span Where?
        %li.main__list__recommend-list
          = image_tag "hungary-4544781_1920.jpg", class: "main__list__recommend-list-image", alt: "place-image"
          %p.recommend-place-name
            %span Hungary
    .main__list__ranking
      %h3.main__list__ranking-title
        %span Recommend ranking
      %ul.main__list__ranking-lists
        %li.ranking-list
          %span Japan
        %li.ranking-list
          %span Cuba
        %li.ranking-list
          %span Brasil
        %li.ranking-list
          %span India
        %li.ranking-list
          %span Spain
        %li.ranking-list
          %span UK
        %li.ranking-list
          %span Morocco
        %li.ranking-list
          %span Costa Rica
        %li.ranking-list
          %span Tahichi
        %li.ranking-list
          %span Bhutan

.footer
  =render "footer"

app/views/casas/new.html.haml
.header-form
  %h1.header-form__title
    =link_to root_path do
      %span casa blanca
.main-form
  = render "form"
  -# .main-form__field
  -#   =form_with model: @casa, local: true do |f|
  -#     %h2.main-form__field__title
  -#       Edit Your Information
  -#     .main-form__field__text
  -#       = f.label :name, class: "main-form__field__text-label"
  -#       = f.text_field :name, placeholder: 'casa name', class: "main-form__field__text-form"
  -#     .main-form__field__text
  -#       = f.label :description, class: "main-form__field__text-label"
  -#       = f.text_field :description, class: 'input-box__description', placeholder: "put address and click search button"
  -#       = icon("fas","search-location", id: "searchAddressBtn")
  -#     .map-area
  -#       #map{:style => "width: 400px; height: 300px;"}
  -#     .description-box
  -#       = f.text_field :latitude, id: "post_latitude", readonly: "readonly"
  -#       =f.text_field :longitude, id: "post_longitude", readonly: "readonly"
  -#     .main-form__field__text
  -#       =f.label :information, class: "main-form__field__text-label"
  -#       =f.text_area :information, placeholder: "main information", class: "main-form__field__text-form"
  -#     .main-form__field__images
  -#       %p.main-form__field__images-title
  -#         Upload your images
  -#         #image-box
  -#           #previews
  -#           #labels
  -#             #label.label-content-0
  -#               -if @casa.persisted?
  -#                 - @casa.images.each_with_index do |image, i|
  -#                   = image_tag image.src.url, data: { index: i}, width: "100", height: "100"
  -#               = f.fields_for :images do |image|
  -#                 = image.label :src ,{id:"label-box--#{image.index}", class:"js-file_group", "data-index" => "#{image.index}"} do
  -#                   =icon("fas","camera",class: "label-box-icon")
  -#                   %pre.label-box__text-visible upload image
  -#                   = image.file_field :src, class: 'js-file'
  -#                 - if @casa.persisted?
  -#                   = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
  -#               - if @casa.persisted?
  -#                 .js-file_group{"data-index" => "#{@casa.images.count}"}
  -#                   = file_field_tag :src, name: "casa[images_attributes][#{@casa.images.count}][src]", class: "js-file"
  -#                   .js-remove delete
  -#     -# .main-form__field__facilities
  -#     -#   = f.label :facilities, class: "main-form__field__facilities-label"
  -#     -#   = collection_check_boxes(:casa, :casa_facilities, Facility.all, :id, :facilityname) do |b|
  -#     -#     = b.label { b.check_box + b.text }
  -#     .main-form__field__important-information
  -#       =f.label :important_information, class: "main-form__field__text-label"
  -#       =f.text_area :important_information, placeholder: "important imformation", class: "main-form__field__text-form"
  -#     .main-form__field__time
  -#       = f.label :check_in
  -#       = f.time_select :check_in, prompt:true, class: "main-form__field__time-select"
  -#     .main-form__field__time
  -#       = f.label :check_out
  -#       = f.time_select :check_out, prompt:true, class: "main-form__field__time-select"
  -#     .main-form__field__important-information
  -#       =f.label :policy, class: "main-form__field__text-label"
  -#       =f.text_area :policy, placeholder: "Policy", class: "main-form__field__text-form"
  -#     .main-form__field__important-information
  -#       =f.label :detail, class: "main-form__field__text-label"
  -#       =f.text_area :detail, placeholder: "detail for your hostel", class: "main-form__field__text-form"
  -#     .main-form__field__important-information
  -#       =f.label :location, class: "main-form__field__text-label"
  -#       =f.text_area :location, placeholder: "location imformation", class: "main-form__field__text-form"
  -#     .main-form__field__important-information
  -#       =f.label :cancel, class: "main-form__field__text-label"
  -#       =f.text_area :cancel, placeholder: "cancel policy", class: "main-form__field__text-form"
  -#     .main-form__field__submit
  -#       = f.submit 'Next', class: "main-form__field__submit-btn"

app/views/casas/show.html.haml
.header
  = render 'header'
.main
  .main__upper
    .main__upper-slick
      -if @casa.images.present?
        - @casa.images.each_with_index do |image, i|
          .slick-list
            = image_tag image.src.url, data: {index: i}, class: "slick-list__image"
      - else
        .slick-list
          = image_tag "pier-569314_1920.jpg", class:"slick-list__image"
        .slick-list
          = image_tag "sunrise-1634197_1920.jpg"
      -# .slick-list
      -#   = image_tag "castle-park-806854_1920.jpg", class: "slick-list__image"
      -# .slick-list
      -#   = image_tag "window-3178666_1920.jpg", class: "slick-list__image"
  .main__search-form
    %input.main__search-form__text{type: "text", placeholder: "Search by city or hostel name..."}
    %input.main__search-form__date-start{type: "date", value: "2020-01-01"}
    %input.main__search-form__date-end{type: "date", value: "2020-01-01"}
    %input.main__search-form__guest{type: "select", prompt: "Guest"}
    %input.main__search-form__btn{type: "submit", value: "Search"}
  .main__casa
    .casa__title
      = @casa.name
    .casa__place
      = @casa.description
  .main__nav
    %ul.main__nav-lists
      %li.nav-list.active
        %span Overview
      %li.nav-list
        %span Reviews
      %li.nav-list
        %span Map
    %ul.main__nav-contents
      %li.nav-content.show
        .nav-content__overview
          .overview-upper
            .overview-upper__introduction
              %p.overview-upper__introduction-text
                = @casa.information
            .overview-upper__images
              %ul.images__lists
                %li.images__list
                  = image_tag "beach-house-1505461_1920.jpg", class: "images__list-image"
                %li.images__list
                  = image_tag "beach-house-1505461_1920.jpg", class: "images__list-image"
                %li.images__list
                  = image_tag "beach-house-1505461_1920.jpg", class: "images__list-image"
                %li.images__list
                  = image_tag "beach-house-1505461_1920.jpg", class: "images__list-image"
          .overview-rating
            %span sample rating
          .overview-information
            %ul.overview-information__lists
              %li.information-list
                .information-list__title
                  %p.information-list__text Facilities
                  .information-list__icon
                    = icon("fas", "angle-down")
                .information-hidden.not-show
                  %ul.information-hidden__lists
                    %li.hidden-list
                      %span Free wifi
                    %li.hidden-list
                      %span Lockers
                    %li.hidden-list
                      %span Breakfast Not Included
                  .information-hidden__icon
                    = icon("fas", "angle-up")
              %li.information-list
                .information-list__title
                  %p.information-list__text  Important Information
                  .information-list__icon
                    = icon("fas", "angle-down")
                .information-hidden.not-show
                  %p.information-hidden__text Inportant Information sample
                  .information-hidden__icon
                    = icon("fas", "angle-up")
              %li.information-list
                .information-list__title
                  %p.information-list__text Check-in / Check-out
                  .information-list__icon
                    = icon("fas", "angle-down")
                .information-hidden.not-show
                  %p.information-hidden__text Earliest check-in: 15:00
                  %p.information-hidden__text Latest Check-out: 11:00
                  .information-hidden__icon
                    = icon("fas", "angle-up")
              %li.information-list
                .information-list__title
                  %p.information-list__text Policies
                  .information-list__icon
                    = icon("fas", "angle-down")
                .information-hidden.not-show
                  %p.information-hidden__text Policies sample
                  .information-hidden__icon
                    = icon("fas", "angle-up")
          .overview-rooms
          .overview-detail
            .overview-detail__text
              %span sample
      %li.nav-content
        .nav-content__reviews
      %li.nav-content
        .nav-content__map
.footer
  = render "footer"